import { ChangeEvent, DragEvent, useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { api } from './api'
import type { Document, Grounding, Project, Schema } from './types'
import './styles.css'

const activeStates = new Set(['queued', 'parsing', 'extracting', 'validating'])
const initialSchema = { type: 'object', properties: {}, required: [] }
const display = (value: unknown) => typeof value === 'string' ? value : JSON.stringify(value ?? null, null, 2)
const fields = (value: unknown, prefix = ''): [string, unknown][] => value && typeof value === 'object' && !Array.isArray(value)
  ? Object.entries(value as Record<string, unknown>).flatMap(([key, item]) => fields(item, prefix ? `${prefix}.${key}` : key)) : [[prefix, value]]
const isBusy = (status?: string) => !!status && activeStates.has(status)
const prettySize = (size: number) => size < 1024 * 1024 ? `${Math.ceil(size / 1024)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`

function App() {
  const [projects, setProjects] = useState<Project[]>([]), [projectId, setProjectId] = useState(''), [documents, setDocuments] = useState<Document[]>([])
  const [document, setDocument] = useState<Document | null>(null), [schemas, setSchemas] = useState<Schema[]>([]), [schemaId, setSchemaId] = useState('')
  const [notice, setNotice] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(true), [tab, setTab] = useState<'parse' | 'schema' | 'review' | 'api'>('parse')
  const [createOpen, setCreateOpen] = useState(false), [projectName, setProjectName] = useState(''), [prompt, setPrompt] = useState(''), [schemaName, setSchemaName] = useState('extraction_schema')
  const [schemaText, setSchemaText] = useState(JSON.stringify(initialSchema, null, 2)), [selectedGrounding, setSelectedGrounding] = useState<Grounding | null>(null)
  const [fileUrl, setFileUrl] = useState('')
  const fileInput = useRef<HTMLInputElement>(null)
  const selectedSchema = schemas.find(schema => schema.id === schemaId)

  const act = async (work: () => Promise<unknown>, success: string) => { setError(''); try { await work(); setNotice(success); await refresh() } catch (e) { setError(e instanceof Error ? e.message : '알 수 없는 오류가 발생했습니다.') } }
  const refresh = async (keepDoc = true) => {
    const list = await api.projects(); setProjects(list); const id = projectId || list[0]?.id || ''
    if (!id) { setLoading(false); return } if (!projectId) setProjectId(id)
    const [nextDocs, nextSchemas] = await Promise.all([api.documents(id), api.schemas(id)]); setDocuments(nextDocs); setSchemas(nextSchemas)
    const docId = document?.id; if (keepDoc && docId) { const next = await api.document(docId); setDocument(next); if (next.status === 'failed') setError(next.error || '처리에 실패했습니다.') }
    setLoading(false)
  }
  useEffect(() => { refresh().catch(e => { setError(e.message); setLoading(false) }) }, [])
  useEffect(() => { if (!projectId) return; setDocument(null); setSchemaId(''); api.documents(projectId).then(setDocuments).catch(e => setError(e.message)); api.schemas(projectId).then(setSchemas).catch(e => setError(e.message)) }, [projectId])
  useEffect(() => { if (!document || !isBusy(document.status)) return; const timer = window.setInterval(() => api.document(document.id).then(setDocument).catch(e => setError(e.message)), 1800); return () => clearInterval(timer) }, [document?.id, document?.status])
  useEffect(() => { if (selectedSchema) setSchemaText(JSON.stringify(selectedSchema.json_schema, null, 2)) }, [selectedSchema?.id])
  useEffect(() => { let active = true, url = ''; setFileUrl(''); if (document) api.file(document.id).then(blob => { url = URL.createObjectURL(blob); if (active) setFileUrl(url) }).catch(e => setError(e.message)); return () => { active = false; if (url) URL.revokeObjectURL(url) } }, [document?.id])
  const upload = (files: FileList | File[]) => projectId && files.length && act(() => api.upload(projectId, Array.from(files)), `${files.length}개 문서를 업로드했습니다.`)
  const chooseDocument = async (id: string) => { setError(''); try { setDocument(await api.document(id)); setTab('parse'); setSelectedGrounding(null) } catch (e) { setError(e instanceof Error ? e.message : '문서를 불러오지 못했습니다.') } }
  const reviewFields = useMemo(() => fields(document?.result), [document?.result])

  if (loading) return <main className="boot"><span className="spinner" /> 작업공간을 불러오는 중입니다…</main>
  return <div className="app">
    <aside className="sidebar"><div className="brand"><span>◆</span> Docraft <small>BETA</small></div><button className="project-switch" onClick={() => setCreateOpen(true)}>{projects.find(p => p.id === projectId)?.name || '프로젝트 만들기'} <b>⌄</b></button>
      <nav><a className="active">▦ 프로젝트</a><a>▤ 문서 <em>{documents.length}</em></a><a>◇ 스키마</a><a>◌ 에이전트</a><a>⌘ API</a></nav><div className="sidebar-foot"><span className="online" /> Local API 연결됨<br/><small>localhost:8000</small><button onClick={() => { const key = window.prompt('X-API-Key (비우면 해제)', '') ?? ''; api.setApiKey(key.trim()); window.location.reload() }}>API 키 설정</button></div></aside>
    <main className="workspace"><header><div><p className="eyebrow">WORKSPACE / {projects.find(p => p.id === projectId)?.name || 'NEW PROJECT'}</p><h1>문서 추출</h1></div><div className="header-actions"><button className="ghost" onClick={() => refresh().catch(e => setError(e.message))}>새로고침</button><button className="primary" onClick={() => fileInput.current?.click()}>+ 문서 업로드</button><input ref={fileInput} type="file" multiple hidden accept=".pdf,image/*,.docx,.xlsx,.csv,.txt,.md" onChange={(e: ChangeEvent<HTMLInputElement>) => e.target.files && upload(e.target.files)} /></div></header>
      {(notice || error) && <div className={`banner ${error ? 'error' : ''}`}>{error || notice}<button onClick={() => { setError(''); setNotice('') }}>×</button></div>}
      {!projects.length ? <Empty onCreate={() => setCreateOpen(true)} /> : <>
        <section className="steps"><Step n="1" label="업로드" done={documents.length > 0} /><Step n="2" label="파싱" done={document?.status === 'parsed' || document?.status === 'needs_review' || document?.status === 'completed'} /><Step n="3" label="스키마" done={!!schemas.length} /><Step n="4" label="추출·검수" done={!!document?.result} /><Step n="5" label="내보내기" done={document?.status === 'completed'} /></section>
        <section className="content"><div className="doc-rail"><div className="rail-head"><b>문서</b><span>{documents.length}</span></div>{documents.length ? documents.map(item => <button className={`document-item ${document?.id === item.id ? 'selected' : ''}`} key={item.id} onClick={() => chooseDocument(item.id)}><span className="file-icon">{item.filename.split('.').pop()?.toUpperCase().slice(0, 3)}</span><span><b>{item.filename}</b><small>{prettySize(item.size)} · <Status value={item.status} /></small></span></button>) : <Dropzone onFiles={upload} />}</div>
          <div className="panel">{document ? <><div className="panel-head"><div><b>{document.filename}</b><small>{document.media_type || '문서'} · {prettySize(document.size)}</small></div><div><Status value={document.status} /> <button disabled={isBusy(document.status)} className="compact" onClick={() => act(() => api.parse(document.id), '파싱 작업을 시작했습니다.')}>파싱</button></div></div><Tabs tab={tab} setTab={setTab} />{tab === 'parse' && <Parse document={document} selected={selectedGrounding} fileUrl={fileUrl} />}{tab === 'schema' && <SchemaPanel prompt={prompt} setPrompt={setPrompt} schemaName={schemaName} setSchemaName={setSchemaName} schemaText={schemaText} setSchemaText={setSchemaText} schemas={schemas} schemaId={schemaId} setSchemaId={setSchemaId} generate={() => act(() => api.generateSchema(projectId, prompt, document.id), 'AI가 스키마 버전을 생성했습니다.')} save={() => act(async () => { const body = JSON.parse(schemaText); await api.createSchema(projectId, schemaName, body) }, '스키마를 저장했습니다.')} extract={() => schemaId && act(() => api.extract(document.id, schemaId), '추출 작업을 시작했습니다.')} disabled={isBusy(document.status)} />}{tab === 'review' && <Review document={document} fileUrl={fileUrl} items={reviewFields} selected={selectedGrounding} onSelect={setSelectedGrounding} onSave={(path, value) => act(() => api.review(document.id, path, value), '수정 내용을 저장했습니다.')} onApprove={() => act(() => api.approve(document.id), '문서를 승인했습니다.')} />}{tab === 'api' && <ApiPanel document={document} schema={selectedSchema} />}</> : <Dropzone onFiles={upload} large />}</div></section></>}
    </main>{createOpen && <CreateProject value={projectName} onChange={setProjectName} onClose={() => setCreateOpen(false)} onCreate={() => act(async () => { const project = await api.createProject(projectName); setProjectId(project.id); setProjectName(''); setCreateOpen(false) }, '프로젝트를 만들었습니다.')} />}</div>
}

const Step = ({ n, label, done }: { n: string; label: string; done: boolean }) => <div className={done ? 'step done' : 'step'}><span>{done ? '✓' : n}</span>{label}</div>
const Status = ({ value }: { value: string }) => <i className={`status ${value}`}>{value.replace('_', ' ')}</i>
const Tabs = ({ tab, setTab }: { tab: string; setTab: (tab: 'parse' | 'schema' | 'review' | 'api') => void }) => <div className="tabs">{([['parse', '원문 · 블록'], ['schema', '스키마'], ['review', '추출 결과'], ['api', 'API']] as const).map(([id, label]) => <button onClick={() => setTab(id)} className={tab === id ? 'active' : ''} key={id}>{label}</button>)}</div>
const Empty = ({ onCreate }: { onCreate: () => void }) => <div className="empty"><span>◇</span><h2>첫 프로젝트를 만들어 시작하세요</h2><p>문서를 업로드하고, 필요한 데이터 구조를 정의하면 AI가 추출과 검수를 이어갑니다.</p><button className="primary" onClick={onCreate}>프로젝트 만들기</button></div>
function Dropzone({ onFiles, large }: { onFiles: (files: FileList | File[]) => void; large?: boolean }) { const over = (e: DragEvent) => { e.preventDefault(); e.currentTarget.classList.add('over') }; return <label className={`dropzone ${large ? 'large' : ''}`} onDragOver={over} onDragLeave={e => e.currentTarget.classList.remove('over')} onDrop={e => { e.preventDefault(); e.currentTarget.classList.remove('over'); onFiles(e.dataTransfer.files) }}><input hidden type="file" multiple accept=".pdf,image/*,.docx,.xlsx,.csv,.txt,.md" onChange={e => e.target.files && onFiles(e.target.files)} /><span>↑</span><b>문서를 끌어 놓으세요</b><small>PDF, 이미지, DOCX, XLSX, CSV, 텍스트 · 여러 파일 가능</small><u>파일 선택</u></label> }
function Parse({ document, selected, fileUrl }: { document: Document; selected: Grounding | null; fileUrl: string }) { const [mode, setMode] = useState<'markdown' | 'blocks'>('markdown'); return <div className="parse"><div className="viewer"><div className="viewer-toolbar"><span>원본 문서</span>{selected && <mark>p.{selected.page || 1} · {selected.text || selected.path}</mark>}</div>{document.media_type?.includes('pdf') ? <iframe title="원본 PDF" src={fileUrl} /> : document.media_type?.startsWith('image/') ? <img src={fileUrl} alt={document.filename} /> : <div className="file-preview">원문 미리보기는 PDF와 이미지에서 지원됩니다.<a href={fileUrl} target="_blank">파일 열기</a></div>}</div><div className="parsed"><div className="switch"><button className={mode === 'markdown' ? 'active' : ''} onClick={() => setMode('markdown')}>Markdown</button><button className={mode === 'blocks' ? 'active' : ''} onClick={() => setMode('blocks')}>Blocks</button></div><pre>{mode === 'markdown' ? document.markdown || '파싱을 실행하면 문서의 Markdown 결과가 여기에 나타납니다.' : display(document.blocks || [])}</pre></div></div> }
function SchemaPanel(props: { prompt: string; setPrompt: (v: string) => void; schemaName: string; setSchemaName: (v: string) => void; schemaText: string; setSchemaText: (v: string) => void; schemas: Schema[]; schemaId: string; setSchemaId: (v: string) => void; generate: () => void; save: () => void; extract: () => void; disabled: boolean }) { return <div className="schema"><div className="schema-tools"><label>AI에게 추출할 구조를 설명하세요<textarea value={props.prompt} onChange={e => props.setPrompt(e.target.value)} placeholder="예: 병원명, 환자명, 진료일자와 진료 내역을 추출해줘" /></label><button className="primary" disabled={!props.prompt} onClick={props.generate}>AI 스키마 생성</button><label>저장된 버전<select value={props.schemaId} onChange={e => props.setSchemaId(e.target.value)}><option value="">새 스키마</option>{props.schemas.map(s => <option key={s.id} value={s.id}>{s.name} v{s.version}</option>)}</select></label></div><div className="editor"><div><label>스키마 이름<input value={props.schemaName} onChange={e => props.setSchemaName(e.target.value)} /></label><div className="field-help">JSON Schema를 직접 편집합니다. 객체·배열과 validation 규칙을 지원합니다.</div></div><textarea aria-label="JSON Schema" value={props.schemaText} onChange={e => props.setSchemaText(e.target.value)} spellCheck={false} /></div><div className="action-row"><button className="ghost" onClick={props.save}>새 버전 저장</button><button className="primary" disabled={!props.schemaId || props.disabled} onClick={props.extract}>이 스키마로 추출 실행 →</button></div></div> }
function Review({ document, fileUrl, items, selected, onSelect, onSave, onApprove }: { document: Document; fileUrl: string; items: [string, unknown][]; selected: Grounding | null; onSelect: (g: Grounding | null) => void; onSave: (path: string, value: unknown) => void; onApprove: () => void }) { const groundingFor = (path: string) => document.groundings?.find(g => g.path === path); return <div className="review"><div className="viewer"><div className="viewer-toolbar"><span>원문 근거</span>{selected && <mark>페이지 {selected.page || 1} · {selected.bbox ? '영역 강조됨' : '텍스트 근거'}</mark>}</div>{document.media_type?.includes('pdf') ? <iframe title="원본 PDF" src={`${fileUrl}#page=${selected?.page || 1}`} /> : document.media_type?.startsWith('image/') ? <img src={fileUrl} alt={document.filename} /> : <div className="file-preview">원본 파일 <a href={fileUrl} target="_blank">열기</a></div>}{selected && <div className="source-card"><b>Source text</b><p>{selected.text || '문서 좌표 정보가 제공되었습니다.'}</p><small>bbox: {selected.bbox?.join(', ') || '—'} · confidence: {selected.confidence ?? '—'}</small></div>}</div><div className="result"><div className="result-head"><div><b>추출된 필드</b><small>{items.length} fields · {document.status === 'needs_review' ? '검수 필요' : '결과 확인'}</small></div><button className="primary" onClick={onApprove} disabled={!document.result}>승인</button></div>{!document.result ? <div className="empty-small">스키마를 선택해 추출을 실행하세요.</div> : items.map(([path, value]) => <Field key={path} path={path} value={value} grounding={groundingFor(path)} onSelect={onSelect} onSave={onSave} />)}<details><summary>Validation · correction history</summary><pre>{display({ validation: document.validation, corrections: document.corrections })}</pre></details><div className="exports"><button onClick={() => api.download(document.id, 'json').catch(() => {})}>JSON 다운로드</button><button onClick={() => api.download(document.id, 'csv').catch(() => {})}>CSV 다운로드</button></div></div></div> }
function Field({ path, value, grounding, onSelect, onSave }: { path: string; value: unknown; grounding?: Grounding; onSelect: (g: Grounding | null) => void; onSave: (path: string, value: unknown) => void }) { const [editing, setEditing] = useState(false), [draft, setDraft] = useState(display(value)); const save = () => { let parsed: unknown = draft; try { parsed = JSON.parse(draft) } catch {} onSave(path, parsed); setEditing(false) }; return <article className={`field ${grounding ? 'grounded' : ''}`} onClick={() => grounding && onSelect(grounding)}><div><small>{path}</small>{editing ? <textarea value={draft} onClick={e => e.stopPropagation()} onChange={e => setDraft(e.target.value)} /> : <code>{display(value)}</code>}</div><aside>{grounding && <><Status value={grounding.status || (grounding.confidence && grounding.confidence < .8 ? 'needs_review' : 'verified')} /><small>{Math.round((grounding.confidence || 0) * 100)}% · p.{grounding.page || 1}</small></>}{editing ? <button onClick={e => { e.stopPropagation(); save() }}>저장</button> : <button onClick={e => { e.stopPropagation(); setEditing(true) }}>수정</button>}</aside></article> }
function ApiPanel({ document, schema }: { document: Document; schema?: Schema }) { const example = `# Upload\ncurl -X POST http://localhost:8000/api/projects/${document.project_id}/documents -H "X-API-Key: $DOCRAFT_API_KEY" -F "files=@${document.filename}"\n\n# Extract\ncurl -X POST http://localhost:8000/api/documents/${document.id}/extract -H "X-API-Key: $DOCRAFT_API_KEY" -H "Content-Type: application/json" -d '{"schema_id":"${schema?.id || '<schema_id>'}"}'\n\n# Poll\ncurl http://localhost:8000/api/documents/${document.id} -H "X-API-Key: $DOCRAFT_API_KEY"`; return <div className="api-panel"><p className="eyebrow">REST API</p><h2>프로덕션에서 같은 워크플로를 실행하세요</h2><p>업로드 후 스키마 ID로 추출을 요청하고 문서 상태를 폴링합니다. API 키는 선택적으로 X-API-Key 헤더에 전달합니다.</p><pre>{example}</pre><div className="api-cards"><div><b>Async processing</b><span>대용량 문서는 문서 상태를 폴링합니다.</span></div><div><b>Export</b><span>JSON 또는 CSV 결과를 다운로드합니다.</span></div><div><b>Webhook</b><span>Webhook과 batch endpoint는 다음 릴리스에서 제공됩니다.</span></div></div></div> }
function CreateProject({ value, onChange, onClose, onCreate }: { value: string; onChange: (v: string) => void; onClose: () => void; onCreate: () => void }) { return <div className="modal-backdrop"><form className="modal" onSubmit={e => { e.preventDefault(); onCreate() }}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">NEW PROJECT</p><h2>프로젝트 만들기</h2><label>프로젝트 이름<input autoFocus value={value} onChange={e => onChange(e.target.value)} placeholder="예: 의료 청구서" /></label><button className="primary" disabled={!value.trim()}>프로젝트 생성</button></form></div> }

createRoot(document.getElementById('root')!).render(<App />)
