import { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import * as pdfjs from 'pdfjs-dist'
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import { api } from './api'
import type { Document, Grounding, Project, Schema } from './types'
import './styles.css'
import './panels.css'

pdfjs.GlobalWorkerOptions.workerSrc = workerUrl
type Tab = 'parse' | 'schema' | 'extract'
const parsed = (doc?: Document | null) => !!doc && ['parsed', 'needs_review', 'completed'].includes(doc.status)
const busy = (doc?: Document | null) => !!doc && ['queued', 'parsing', 'extracting', 'validating'].includes(doc.status)
const json = (value: unknown) => JSON.stringify(value ?? null, null, 2)
const err = (value: unknown) => value instanceof Error ? value.message : '요청에 실패했습니다.'
const path = () => location.pathname.match(/^\/projects\/([^/]+)$/)?.[1] || ''
const flatten = (value: unknown, parent = ''): [string, unknown][] => value && typeof value === 'object' ? Object.entries(value).flatMap(([key, part]) => flatten(part, parent ? `${parent}.${key}` : key)) : [[parent, value]]

function App() {
  const [projectId, setProjectId] = useState(path), [section, setSection] = useState(location.pathname === '/projects' ? 'projects' : path() ? 'detail' : 'new')
  const [projects, setProjects] = useState<Project[]>([]), [project, setProject] = useState<Project | null>(null), [docs, setDocs] = useState<Document[]>([]), [doc, setDoc] = useState<Document | null>(null)
  const [schemas, setSchemas] = useState<Schema[]>([]), [schemaId, setSchemaId] = useState(''), [schemaName, setSchemaName] = useState('extraction_schema'), [schemaText, setSchemaText] = useState(json({ type: 'object', properties: {} })), [advanced, setAdvanced] = useState(false)
  const [tab, setTab] = useState<Tab>('parse'), [name, setName] = useState(''), [prompt, setPrompt] = useState(''), [files, setFiles] = useState<File[]>([]), [search, setSearch] = useState('')
  const [selected, setSelected] = useState<Grounding | null>(null), [fileUrl, setFileUrl] = useState(''), [notice, setNotice] = useState(''), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  const [sourceCollapsed, setSourceCollapsed] = useState(false), [workCollapsed, setWorkCollapsed] = useState(false)
  const uploadInput = useRef<HTMLInputElement>(null), selectedSchema = schemas.find(item => item.id === schemaId)
  const go = (next: 'new' | 'projects' | 'detail', id = '') => { history.pushState({}, '', next === 'detail' ? `/projects/${id}` : next === 'projects' ? '/projects' : '/'); setSection(next); setProjectId(id); setError(''); setNotice('') }
  const refreshProjects = () => api.projects().then(setProjects)
  const refreshDetail = async (id: string, documentId?: string) => { const [p, d, s] = await Promise.all([api.project(id), api.documents(id), api.schemas(id)]); setProject(p); setDocs(d); setSchemas(s); const target = documentId || (doc?.project_id === id ? doc.id : d[0]?.id); setDoc(target ? await api.document(target) : null) }
  useEffect(() => { const pop = () => { const id = path(); setProjectId(id); setSection(id ? 'detail' : location.pathname === '/projects' ? 'projects' : 'new') }; addEventListener('popstate', pop); return () => removeEventListener('popstate', pop) }, [])
  useEffect(() => { refreshProjects().catch(e => setError(err(e))) }, [section])
  useEffect(() => { if (projectId) refreshDetail(projectId).catch(e => setError(err(e))) }, [projectId])
  useEffect(() => { if (!busy(doc)) return; const timer = setInterval(() => api.document(doc!.id).then(setDoc).catch(e => setError(err(e))), 1800); return () => clearInterval(timer) }, [doc?.id, doc?.status])
  useEffect(() => { if (doc) setDocs(current => current.map(item => item.id === doc.id ? doc : item)) }, [doc])
  useEffect(() => { setSchemaText(json(selectedSchema?.json_schema || { type: 'object', properties: {} })); if (selectedSchema) setSchemaName(selectedSchema.name) }, [selectedSchema?.id])
  useEffect(() => { let active = true, url = ''; setFileUrl(''); if (doc) api.file(doc.id).then(blob => { url = URL.createObjectURL(blob); if (active) setFileUrl(url) }).catch(e => setError(err(e))); return () => { active = false; if (url) URL.revokeObjectURL(url) } }, [doc?.id])
  const run = async (job: () => Promise<unknown>, success: string, documentId?: string) => { setLoading(true); setError(''); try { await job(); setNotice(success); await refreshProjects(); if (projectId) await refreshDetail(projectId, documentId) } catch (e) { setError(err(e)) } finally { setLoading(false) } }
  const create = () => run(async () => { const p = await api.createProject(name.trim() || `새 프로젝트 ${new Date().toLocaleDateString('ko-KR')}`); if (files.length) await api.upload(p.id, files); setFiles([]); setName(''); go('detail', p.id) }, '프로젝트를 만들었습니다.')
  const upload = (list: FileList | File[]) => { const items = Array.from(list); if (!projectId) setFiles(items); else run(() => api.upload(projectId, items), `${items.length}개 파일을 업로드했습니다.`) }
  const rename = (p: Project) => { const value = promptProject(p.name); if (value && value !== p.name) run(() => api.updateProject(p.id, value), '이름을 변경했습니다.') }
  const remove = (p: Project) => { if (confirm(`「${p.name}」 프로젝트와 그 문서·스키마를 삭제하시겠습니까?`)) run(async () => { await api.deleteProject(p.id); if (projectId === p.id) go('projects') }, '프로젝트를 삭제했습니다.') }
  const saveSchema = () => run(async () => { const body = JSON.parse(schemaText); const s = selectedSchema ? await api.updateSchema(selectedSchema.id, schemaName, body) : await api.createSchema(projectId, schemaName, body); setSchemaId(s.id) }, '스키마를 저장했습니다.')
  const generate = () => doc && run(async () => { const s = await api.generateSchema(projectId, prompt, doc.id); setSchemaId(s.id) }, '스키마를 생성했습니다.')
  const extract = () => doc && schemaId && run(() => api.extract(doc.id, schemaId), '추출을 시작했습니다.', doc.id)
  const toggleSource = () => { if (!sourceCollapsed && workCollapsed) setWorkCollapsed(false); setSourceCollapsed(!sourceCollapsed) }
  const toggleWork = () => { if (!workCollapsed && sourceCollapsed) setSourceCollapsed(false); setWorkCollapsed(!workCollapsed) }
  return <div className="app"><aside className="rail"><button className="logo" title="Docraft" onClick={() => go('new')}>◈</button><button className={section === 'new' ? 'active' : ''} title="새 프로젝트" onClick={() => go('new')}>＋</button><button className={section !== 'new' ? 'active' : ''} title="프로젝트 목록" onClick={() => go('projects')}>▣</button><div className="spacer" /><button title="API 키" onClick={() => { api.setApiKey(window.prompt('API 키 (비우면 해제)', '')?.trim() || ''); location.reload() }}>⚿</button></aside><div className="app-main"><header className="topbar"><button className="brand" onClick={() => go('new')}>Docraft</button><span className="muted">/ {section === 'detail' ? project?.name : section === 'projects' ? '프로젝트 목록' : '새 프로젝트'}</span><div className="spacer" /><button className="quiet" onClick={() => { refreshProjects(); if (projectId) refreshDetail(projectId) }}>↻ 새로고침</button></header>{(notice || error) && <div className={`toast ${error ? 'error' : ''}`}>{error || notice}<button onClick={() => { setNotice(''); setError('') }}>×</button></div>}
  {section === 'new' && <main className="home"><p className="eyebrow">DOCUMENT WORKSPACE</p><h1>문서를 신뢰할 수 있는 데이터로</h1><p className="muted">파일을 올리고, 필요한 항목을 정의해 추출 결과를 확인하세요.</p><div className="create-card"><div className="file-art"><span>PDF<br/>━━━━<br/>━━━━</span><span>DOC<br/>━━━━<br/>━━━━</span><span>IMG<br/>━━━━<br/>━━━━</span></div><h2>새 프로젝트 시작하기</h2><p className="muted">PDF, 이미지, 문서, 스프레드시트를 업로드할 수 있습니다.</p><input placeholder="프로젝트 이름 (선택)" value={name} onChange={e => setName(e.target.value)} /><label className="drop" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); upload(e.dataTransfer.files) }}><input hidden type="file" multiple onChange={e => e.target.files && upload(e.target.files)} /><b>＋ 파일 선택</b> 또는 여기에 끌어 놓기</label>{files.length > 0 && <small>선택된 파일: {files.map(f => f.name).join(', ')}</small>}<div className="card-footer"><span>나중에 파일을 추가할 수도 있습니다.</span><button className="primary" disabled={loading} onClick={create}>프로젝트 만들기 →</button></div></div><div className="recent-title"><h2>최근 프로젝트</h2><button onClick={() => go('projects')}>전체 보기 →</button></div><div className="recent">{projects.slice(0, 4).map(p => <button key={p.id} onClick={() => go('detail', p.id)}><span className="folder">▣</span><span>{p.name}<small>{new Date(p.created_at).toLocaleDateString('ko-KR')}</small></span><b>›</b></button>)}{!projects.length && <p className="muted">아직 프로젝트가 없습니다.</p>}</div></main>}
  {section === 'projects' && <main className="projects"><div className="projects-head"><div><p className="eyebrow">WORKSPACE</p><h1>프로젝트 목록 <small>{projects.length}</small></h1><p className="muted">진행 중인 프로젝트를 열거나 관리하세요.</p></div><button className="primary" onClick={() => go('new')}>＋ 새 프로젝트</button></div><input className="search" placeholder="프로젝트 검색" value={search} onChange={e => setSearch(e.target.value)} /><div className="project-rows">{projects.filter(p => p.name.toLowerCase().includes(search.toLowerCase())).map(p => <div className="project-row" key={p.id}><button className="project-open" onClick={() => go('detail', p.id)}><span className="folder">▣</span><span><b>{p.name}</b><small>생성 {new Date(p.created_at).toLocaleDateString('ko-KR')}</small></span></button><button onClick={() => rename(p)}>이름 변경</button><button className="danger" onClick={() => remove(p)}>삭제</button></div>)}{!projects.length && <div className="empty">프로젝트가 없습니다.</div>}</div></main>}
  {section === 'detail' && <main className="detail">
    <div className="detail-bar"><div><button onClick={() => go('projects')}>프로젝트 목록</button><span>›</span><b>{project?.name}</b><span>›</span><span>{doc?.filename || '문서 선택'}</span></div><div><button disabled={!doc?.result} onClick={() => doc && api.download(doc.id, 'json').catch(e => setError(err(e)))}>JSON 내보내기</button><button disabled={!doc?.result} onClick={() => doc && api.download(doc.id, 'csv').catch(e => setError(err(e)))}>CSV</button></div></div>
    <div className={`detail-grid ${sourceCollapsed ? 'source-collapsed' : ''} ${workCollapsed ? 'work-collapsed' : ''}`}>
      <section className={`document-area ${sourceCollapsed ? 'collapsed' : ''}`} aria-label="원문 패널">
        {sourceCollapsed && <button className="collapsed-handle" aria-label="원문 패널 펼치기" aria-expanded={false} onClick={toggleSource}><span>›</span><b>원문</b></button>}
        <div className="document-content" hidden={sourceCollapsed}>
          <div className="document-title"><b>{doc?.filename || '파일 없음'}</b><small>{doc?.status}</small><button className="panel-toggle" aria-label="원문 패널 접기" aria-expanded={true} onClick={toggleSource}>‹ 접기</button></div>
          <Preview doc={doc} fileUrl={fileUrl} selected={selected} />
          <div className="files"><div className="files-title"><b>파일 ({docs.length})</b><button onClick={() => uploadInput.current?.click()}>＋ 파일 추가</button><input hidden ref={uploadInput} type="file" multiple onChange={e => e.target.files && upload(e.target.files)} /></div><div className="file-list">{docs.map(item => <button className={item.id === doc?.id ? 'active' : ''} key={item.id} onClick={() => api.document(item.id).then(next => { setDoc(next); setSelected(null) }).catch(e => setError(err(e)))}><span className="folder">{item.filename.split('.').pop()?.toUpperCase().slice(0, 3)}</span><span>{item.filename}<small>{item.status}</small></span></button>)}{!docs.length && <p className="muted">파일을 추가하세요.</p>}</div></div>
        </div>
      </section>
      <section className={`work-area ${workCollapsed ? 'collapsed' : ''}`} aria-label="작업 패널">
        {workCollapsed && <button className="collapsed-handle" aria-label="작업 패널 펼치기" aria-expanded={false} onClick={toggleWork}><span>‹</span><b>{tab === 'schema' ? '스키마' : tab === 'extract' ? '추출 결과' : '파싱 결과'}</b></button>}
        <div className="work-content" hidden={workCollapsed}>
        <div className="tabs"><button className={tab === 'parse' ? 'active' : ''} onClick={() => setTab('parse')}>▧ Parse</button><button className={tab === 'schema' ? 'active' : ''} onClick={() => setTab('schema')}>▥ Schema</button><button className={tab === 'extract' ? 'active' : ''} onClick={() => setTab('extract')}>▤ Extract</button><button className="panel-toggle" aria-label="작업 패널 접기" aria-expanded={true} onClick={toggleWork}>접기 ›</button></div>
  {tab === 'parse' && <div className="pane"><div className="pane-title"><div><h2>파싱 결과</h2><p className="muted">문서의 텍스트와 구조를 확인합니다.</p></div><button className="primary" disabled={!doc || busy(doc) || loading} onClick={() => doc && run(() => api.parse(doc.id), '파싱을 시작했습니다.', doc.id)}>Parse 실행</button></div>{doc?.error && <p className="inline-error">{doc.error}</p>}<details open><summary>Markdown</summary><pre>{doc?.markdown || '파싱 결과가 아직 없습니다.'}</pre></details><details><summary>블록 JSON</summary><pre>{json(doc?.blocks || [])}</pre></details></div>}
  {tab === 'schema' && <div className="pane"><div className="pane-title"><div><h2>스키마 구성</h2><p className="muted">파싱된 문서를 참고 자료로 스키마를 제안받으세요.</p></div></div><div className="reference"><b>참고 파일</b><div className="reference-doc"><span className="folder">{doc?.filename.split('.').pop()?.toUpperCase().slice(0, 3) || '—'}</span><span>{doc?.filename || '왼쪽에서 파일을 선택하세요'}<small>PDF · 이미지 · 문서 · 스프레드시트</small></span></div><label>추출 지침 <span className="muted">(선택)</span><textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="예: 거래처, 날짜, 금액과 품목별 내역" /></label><p className="muted">{parsed(doc) ? '파싱 결과를 바탕으로 스키마를 생성할 수 있습니다.' : '먼저 Parse를 실행해 문서 처리를 완료하세요.'}</p><button className="primary" disabled={!parsed(doc) || loading} onClick={generate}>참고 자료로 스키마 생성 ↗</button></div><div className="schema-title"><h2>스키마</h2><select aria-label="저장된 스키마" value={schemaId} onChange={e => setSchemaId(e.target.value)}><option value="">새 스키마</option>{schemas.map(s => <option key={s.id} value={s.id}>{s.name} v{s.version}</option>)}</select><div className="spacer" /><button className="primary" disabled={!parsed(doc) || !schemaId || loading} onClick={extract}>현재 파일 추출 →</button></div><div className="schema-editor"><label>스키마 이름<input value={schemaName} onChange={e => setSchemaName(e.target.value)} /></label>{!advanced && <VisualSchema value={schemaText} onChange={setSchemaText} />}<button className="link" onClick={() => setAdvanced(!advanced)}>{advanced ? '시각 편집기로 돌아가기' : '고급 JSON 편집'}</button>{advanced && <textarea className="json-editor" aria-label="JSON Schema" value={schemaText} onChange={e => setSchemaText(e.target.value)} spellCheck={false} />}<div className="editor-actions"><button className="quiet danger" disabled={!selectedSchema || loading} onClick={() => selectedSchema && confirm('이 스키마 버전을 삭제하시겠습니까?') && run(async () => { await api.deleteSchema(selectedSchema.id); setSchemaId('') }, '스키마를 삭제했습니다.')}>삭제</button><button className="primary" disabled={loading} onClick={saveSchema}>{selectedSchema ? '새 버전으로 저장' : '스키마 저장'}</button></div></div></div>}
  {tab === 'extract' && <div className="pane"><div className="pane-title"><div><h2>추출 결과</h2><p className="muted">필드를 클릭하면 원문 근거가 강조됩니다.</p></div><button className="primary" disabled={!parsed(doc) || !schemaId || loading} onClick={extract}>추출 실행</button></div><div className="extract-select"><select aria-label="추출할 스키마" value={schemaId} onChange={e => setSchemaId(e.target.value)}><option value="">스키마 선택</option>{schemas.map(s => <option key={s.id} value={s.id}>{s.name} v{s.version}</option>)}</select><small>{doc?.status}</small></div>{doc?.result ? <><div className="results">{flatten(doc.result).map(([key, value]) => <Result key={key} path={key} value={value} grounding={doc.groundings?.find(g => g.path === key)} select={setSelected} save={next => run(() => api.review(doc.id, key, next), '수정 내용을 저장했습니다.', doc.id)} />)}</div>{selected && <div className="source"><b>원문 근거</b><p>{selected.text || '근거 텍스트 없음'}</p><small>페이지 {selected.page || 1} · 신뢰도 {Math.round((selected.confidence || 0) * 100)}%</small></div>}<details><summary>검증 · 수정 기록</summary><pre>{json({ validation: doc.validation, corrections: doc.corrections })}</pre></details><div className="editor-actions"><button onClick={() => api.download(doc.id, 'json').catch(e => setError(err(e)))}>JSON</button><button onClick={() => api.download(doc.id, 'csv').catch(e => setError(err(e)))}>CSV</button><button className="primary" onClick={() => run(() => api.approve(doc.id), '결과를 승인했습니다.', doc.id)}>승인</button></div></> : <div className="empty">스키마를 선택하고 추출을 실행하세요.</div>}</div>}
  </div>
  </section></div></main>}</div></div>
}
const promptProject = (name: string) => window.prompt('새 프로젝트 이름', name)?.trim()

function VisualSchema({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  let schema: Record<string, any>; try { schema = JSON.parse(value) } catch { return <p className="inline-error">JSON 형식이 올바르지 않습니다. 고급 편집에서 수정하세요.</p> }
  const update = (action: (copy: Record<string, any>) => void) => { const copy = structuredClone(schema); copy.properties ||= {}; action(copy); onChange(json(copy)) }
  const rows = (properties: Record<string, any>, parent: string[] = []): JSX.Element[] => Object.entries(properties).flatMap(([key, def]) => { const get = (copy: Record<string, any>) => parent.reduce((node, part) => node.properties[part].type === 'array' ? node.properties[part].items : node.properties[part], copy); const type = def.type === 'array' && def.items?.type === 'object' ? 'array' : def.type || 'string'; return [<div className="schema-field" key={[...parent, key].join('.')} style={{ paddingLeft: parent.length * 20 }}><input aria-label="필드 이름" value={key} onChange={e => update(copy => { const target = get(copy); const next = e.target.value; if (!next || next === key) return; target.properties = Object.fromEntries(Object.entries(target.properties).map(([name, item]) => [name === key ? next : name, item])); target.required = (target.required || []).map((name: string) => name === key ? next : name) })} /><select aria-label="필드 유형" value={type} onChange={e => update(copy => { const next = e.target.value; get(copy).properties[key] = next === 'array' ? { type: 'array', items: { type: 'object', properties: {} } } : next === 'object' ? { type: 'object', properties: {} } : { type: next } })}><option value="string">문자열</option><option value="number">숫자</option><option value="boolean">참/거짓</option><option value="object">객체</option><option value="array">객체 목록</option></select><button title="삭제" onClick={() => update(copy => { const target = get(copy); delete target.properties[key]; target.required = (target.required || []).filter((name: string) => name !== key) })}>×</button></div>, ...(def.type === 'object' ? rows(def.properties || {}, [...parent, key]) : type === 'array' ? rows(def.items.properties || {}, [...parent, key]) : [])] })
  return <div className="visual-schema"><div className="visual-head"><b>필드 구조</b><small>{Object.keys(schema.properties || {}).length}개 최상위 필드</small></div>{rows(schema.properties || {})}<button className="link" onClick={() => update(copy => { let key = '새_필드', n = 2; while (copy.properties[key]) key = `새_필드_${n++}`; copy.properties[key] = { type: 'string' } })}>＋ 필드 추가</button></div>
}

function Result({ path, value, grounding, select, save }: { path: string; value: unknown; grounding?: Grounding; select: (g: Grounding | null) => void; save: (value: unknown) => void }) { const [editing, setEditing] = useState(false), [draft, setDraft] = useState(json(value)); useEffect(() => setDraft(json(value)), [value]); return <div className="result-field" onClick={() => grounding && select(grounding)}><div><small>{path}</small>{editing ? <textarea value={draft} onClick={e => e.stopPropagation()} onChange={e => setDraft(e.target.value)} /> : <b>{typeof value === 'string' ? value : json(value)}</b>}</div><div><small>{grounding?.page ? `p.${grounding.page}` : ''}</small>{editing ? <button onClick={e => { e.stopPropagation(); let next: unknown = draft; try { next = JSON.parse(draft) } catch {} save(next); setEditing(false) }}>저장</button> : <button onClick={e => { e.stopPropagation(); setEditing(true) }}>수정</button>}</div></div> }

function Preview({ doc, fileUrl, selected }: { doc: Document | null; fileUrl: string; selected: Grounding | null }) {
  const [page, setPage] = useState(1), [pages, setPages] = useState(1), [zoom, setZoom] = useState(1), [size, setSize] = useState({ width: 1, height: 1 }), [natural, setNatural] = useState({ width: 1, height: 1 }), canvas = useRef<HTMLCanvasElement>(null)
  useEffect(() => { setPage(1); setZoom(1); setNatural({ width: 1, height: 1 }) }, [doc?.id]); useEffect(() => { if (selected?.page) setPage(selected.page) }, [selected?.page]); useEffect(() => { if (doc?.media_type?.startsWith('image/')) setSize({ width: natural.width * zoom, height: natural.height * zoom }) }, [natural, zoom, doc?.media_type])
  useEffect(() => { if (!fileUrl || !doc?.media_type?.includes('pdf')) return; let cancelled = false, rendering: ReturnType<pdfjs.PDFPageProxy['render']> | undefined; (async () => { const pdf = await pdfjs.getDocument(fileUrl).promise; if (cancelled) return; setPages(pdf.numPages); const p = await pdf.getPage(Math.min(page, pdf.numPages)), viewport = p.getViewport({ scale: 1.5 * zoom }), target = canvas.current; if (!target || cancelled) return; target.width = viewport.width; target.height = viewport.height; setSize({ width: viewport.width, height: viewport.height }); rendering = p.render({ canvasContext: target.getContext('2d')!, viewport }); await rendering.promise })().catch(() => {}); return () => { cancelled = true; rendering?.cancel() } }, [doc?.id, fileUrl, page, zoom])
  const box = (g: Grounding) => { const b = g.bbox; if (!b || b.length < 4 || b[2] <= b[0] || b[3] <= b[1]) return null; const image = doc?.media_type?.startsWith('image/'); const max = Math.max(...b); const factor = max <= 1 ? 1 : image && max <= 1000 ? .001 : !image ? 1.5 * zoom : 0; if (!factor) return null; return max <= 1 || image ? { left: b[0] * factor * size.width, top: b[1] * factor * size.height, width: (b[2] - b[0]) * factor * size.width, height: (b[3] - b[1]) * factor * size.height } : { left: b[0] * factor, top: b[1] * factor, width: (b[2] - b[0]) * factor, height: (b[3] - b[1]) * factor } }
  const parseBoxes = (doc?.blocks || []).filter((block): block is { page?: number; bbox: number[] } => !!block && typeof block === 'object' && !Array.isArray(block) && Array.isArray((block as { bbox?: unknown }).bbox)).map(block => ({ path: 'parse-block', page: block.page, bbox: block.bbox }))
  const boxes = [...parseBoxes, ...(doc?.groundings || [])].filter(g => (g.page || 1) === page)
  return <div className="preview"><div className="preview-toolbar"><b>원본 문서</b><div><button disabled={page <= 1} onClick={() => setPage(page - 1)}>‹</button>{page} / {pages}<button disabled={page >= pages} onClick={() => setPage(page + 1)}>›</button><button onClick={() => setZoom(Math.max(.5, zoom - .25))}>−</button>{Math.round(zoom * 100)}%<button onClick={() => setZoom(Math.min(2.5, zoom + .25))}>＋</button></div></div><div className="preview-scroll">{doc && fileUrl ? doc.media_type?.includes('pdf') ? <div className="page-image" style={size}><canvas ref={canvas} />{boxes.map((g, i) => { const rect = box(g); return rect && <span key={i} className={`bbox ${selected?.path === g.path ? 'selected' : ''}`} style={rect} /> })}</div> : doc.media_type?.startsWith('image/') ? <div className="page-image" style={size}><img src={fileUrl} alt={doc.filename} style={{ width: size.width, height: size.height }} onLoad={e => { const image = e.currentTarget; setNatural({ width: image.naturalWidth, height: image.naturalHeight }) }} />{boxes.map((g, i) => { const rect = box(g); return rect && <span key={i} className={`bbox ${selected?.path === g.path ? 'selected' : ''}`} style={rect} /> })}</div> : <div className="empty">미리보기를 지원하지 않는 파일입니다. <a href={fileUrl} download={doc.filename}>원본 다운로드</a></div> : <div className="empty">파일을 선택하면 원본이 표시됩니다.</div>}</div></div>
}

createRoot(document.getElementById('root')!).render(<App />)
