import { useState } from 'react'
import { Icon, statusText } from './ui'
import type { Document, Format, Schema } from './types'

type Column = { path: string; title: string; list: boolean }
// 스키마의 leaf 필드를 점 경로 열로 펼친다. 객체 목록(array of object)은 한 열로 둔다.
const columns = (properties: Record<string, any> = {}, parent = ''): Column[] => Object.entries(properties).flatMap(([key, def]) => { const path = parent ? `${parent}.${key}` : key; return def?.type === 'object' && def.properties ? columns(def.properties, path) : [{ path, title: def?.title || path, list: def?.type === 'array' && def.items?.type === 'object' }] })
const pick = (value: unknown, path: string) => path.split('.').reduce<any>((node, key) => node?.[key], value)
const text = (value: unknown, list: boolean) => value == null ? '' : list && Array.isArray(value) ? `${value.length}건` : typeof value === 'object' ? JSON.stringify(value) : String(value)

export default function ResultsTable({ docs, schemas, schemaId, loading, open, extract, download }: { docs: Document[]; schemas: Schema[]; schemaId: string; loading: boolean; open: (id: string) => void; extract: (schemaId: string, ids: string[]) => void; download: (format: Format, schemaId?: string) => void }) {
  const [picked, setPicked] = useState(''), [query, setQuery] = useState(''), [status, setStatus] = useState(''), [sort, setSort] = useState<[string, number]>(['filename', 1]), [checked, setChecked] = useState<string[]>([])
  const counts = docs.reduce<Record<string, number>>((all, d) => d.schema_id ? { ...all, [d.schema_id]: (all[d.schema_id] || 0) + 1 } : all, {})
  const used = Object.keys(counts).filter(id => schemas.some(s => s.id === id)).sort((a, b) => counts[b] - counts[a])[0]
  const schema = schemas.find(s => s.id === (picked || used || schemaId)), cols = columns(schema?.json_schema.properties as Record<string, any>)
  const own = (d: Document) => !!schema && schemas.some(s => s.id === d.schema_id && s.name === schema.name)
  const raw = (d: Document, c: Column) => own(d) ? pick(d.result, c.path) : undefined, cell = (d: Document, c?: Column) => c ? text(raw(d, c), c.list) : ''
  // validation 경로는 JSON Pointer(/a/0/b)이므로 점 경로로 바꿔 해당 열 또는 그 하위와 맞춘다.
  const issue = (d: Document, c: Column) => own(d) ? (d.validation || []).filter(v => { const p = v.path.slice(1).replace(/\//g, '.'); return p === c.path || p.startsWith(`${c.path}.`) }).map(v => v.message).join('\n') : ''
  const key = (d: Document, k: string) => k === 'filename' ? d.filename : k === 'status' ? statusText[d.status] || d.status : cell(d, cols.find(c => c.path === k))
  const q = query.trim().toLowerCase(), visible = docs.filter(d => (!status || d.status === status) && (!q || [d.filename, ...cols.map(c => cell(d, c))].some(v => v.toLowerCase().includes(q)))).sort((a, b) => sort[1] * key(a, sort[0]).localeCompare(key(b, sort[0]), 'ko', { numeric: true }))
  const ids = checked.filter(id => docs.some(d => d.id === id)), all = visible.length > 0 && visible.every(d => ids.includes(d.id))
  const head = (k: string, label: string) => <th key={k} aria-sort={sort[0] === k ? sort[1] > 0 ? 'ascending' : 'descending' : undefined}><button onClick={() => setSort([k, sort[0] === k ? -sort[1] : 1])}>{label}<span>{sort[0] === k ? sort[1] > 0 ? '↑' : '↓' : ''}</span></button></th>
  return <section className="results-view" aria-label="결과 표"><div className="results-toolbar"><label>스키마<select value={schema?.id || ''} onChange={e => setPicked(e.target.value)}><option value="">스키마 선택</option>{schemas.map(s => <option key={s.id} value={s.id}>{s.name} v{s.version}</option>)}</select></label><input type="search" aria-label="표 검색" placeholder="파일명·값 검색" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="상태 필터" value={status} onChange={e => setStatus(e.target.value)}><option value="">전체 상태</option>{[...new Set(docs.map(d => d.status))].map(s => <option key={s} value={s}>{statusText[s] || s}</option>)}</select><span className="results-count">{visible.length} / {docs.length}개</span><div className="results-actions"><span className="results-export" aria-label="프로젝트 내보내기">{(['csv', 'xlsx', 'json'] as const).map(f => <button key={f} className="quiet" disabled={!docs.length} onClick={() => download(f, schema?.id)}>{f.toUpperCase()}</button>)}</span><button className="primary" disabled={!ids.length || !schema || loading} onClick={() => { extract(schema!.id, ids); setChecked([]) }}>선택 문서 추출 ({ids.length}) <Icon name="spark" size={16} /></button></div></div>
    <div className="results-scroll"><table className="results-table"><thead><tr><th className="check"><input type="checkbox" aria-label="보이는 문서 모두 선택" checked={all} disabled={!visible.length} onChange={() => setChecked(all ? ids.filter(id => !visible.some(d => d.id === id)) : [...new Set([...ids, ...visible.map(d => d.id)])])} /></th>{head('filename', '파일명')}{head('status', '상태')}{cols.map(c => head(c.path, c.title))}</tr></thead>
      <tbody>{visible.map(d => <tr key={d.id} className={ids.includes(d.id) ? 'checked' : ''}><td className="check"><input type="checkbox" aria-label={`${d.filename} 선택`} checked={ids.includes(d.id)} onChange={() => setChecked(ids.includes(d.id) ? ids.filter(id => id !== d.id) : [...ids, d.id])} /></td><td className="name"><button title="문서 작업에서 열기" onClick={() => open(d.id)}>{d.filename}</button></td><td><span className={`status-pill ${d.status}`}>{statusText[d.status] || d.status}</span></td>{cols.map(c => { const message = issue(d, c), value = raw(d, c); return <td key={c.path} className={message ? 'issue' : ''} title={[message, value == null ? '' : c.list ? JSON.stringify(value) : cell(d, c)].filter(Boolean).join('\n') || undefined}>{cell(d, c)}</td> })}</tr>)}</tbody></table>
      {!visible.length && <div className="empty">{docs.length ? '조건에 맞는 문서가 없습니다.' : '문서가 없습니다. 문서 작업에서 파일을 추가하세요.'}</div>}</div></section>
}
