export type Status = 'uploaded' | 'queued' | 'parsing' | 'parsed' | 'extracting' | 'validating' | 'needs_review' | 'completed' | 'failed'
export type Project = { id: string; name: string; description?: string; created_at: string }
export type AiStatus = { configured: boolean; provider: string | null; model: string | null; mode: 'provider' | 'local'; ocr?: { configured: boolean; provider: string | null; model: string; ready: boolean; mode?: 'library' | 'paddle' } }
export type Schema = { id: string; project_id: string; name: string; version: number; json_schema: Record<string, unknown>; created_at: string }
export type BlockType = 'text' | 'heading' | 'table' | 'figure' | 'marginalia' | 'formula'
export type Block = { type: BlockType; label?: string; text: string; page?: number; bbox?: number[]; page_size?: number[]; rows?: string[][]; spans?: number[][]; lines?: { text: string; bbox: number[] }[] }
export type Grounding = { path: string; page?: number; bbox?: number[]; text?: string; confidence?: number; status?: string }
export type Document = { id: string; project_id: string; filename: string; media_type: string; size: number; status: Status; error?: string; markdown?: string; blocks?: Block[]; result?: unknown; schema_id?: string; approved_at?: string; groundings?: Grounding[]; validation?: { path: string; code?: string; message: string }[]; corrections?: unknown[]; parse_options?: ParseOptions; created_at: string; updated_at: string }
export type Format = 'json' | 'csv' | 'xlsx'
export type ParseOptions = { pages?: string | null; provider?: 'auto' | 'library' | 'paddle'; table_format?: 'markdown' | 'html' }
